#include  "TLV3502AID.h"


void TLV3502AID_init(void)
{
	RCC->AHB4ENR|=1<<0;    			//使能PORTA时钟 
	RCC->AHB4ENR|=1<<2;    			//使能PORTC时钟 
	GPIO_Set(GPIOA,PIN6|PIN8,GPIO_MODE_IN,GPIO_OTYPE_OD,GPIO_SPEED_HIGH,GPIO_PUPD_NONE);
	GPIO_Set(GPIOC,PIN6|PIN7,GPIO_MODE_IN,GPIO_OTYPE_OD,GPIO_SPEED_HIGH,GPIO_PUPD_NONE);
}

